version: "3"
services:
  moviepark-traefik:
    image:
      traefik:v2.2
    container_name: moviepark-traefik
    restart: always
    command:
      - "--log.level=ERROR"
      - "--api.dashboard=true"
      #- "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=moviepark-network"
      - "--entrypoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`dashboard.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=lazar:$$2y$$10$$ciI3Y86xGCi9wyiCYLuHNuttnHs9HmWOWTXmeesFlVHt0JASoYGwC"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - moviepark-network
  moviepark-client:
    build:
      context: ./client
      dockerfile: Dockerfile.staging
    volumes:
      - ./client:/home/node/app
      - movieparkNuxtNM:/home/node/app/node_modules
    container_name: moviepark-client
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moviepark-client.rule=Host(`localhost`)"
      - "traefik.http.routers.moviepark-client.entrypoints=web"
    restart: always
    depends_on:
      - moviepark-traefik
      - moviepark-server
    networks:
      - moviepark-network
  moviepark-server:
    build:
      context: ./server
      dockerfile: Dockerfile.staging
    volumes:
      - ./server:/home/node/app
      - movieparkAdonisNM:/home/node/app/node_modules
    container_name: moviepark-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moviepark-server.rule=Host(`api.localhost`)"
      - "traefik.http.routers.moviepark-server.entrypoints=web"
    restart: always
    depends_on:
      - moviepark-traefik
    networks:
      - moviepark-network
networks:
  moviepark-network:
    driver: bridge
volumes:
  movieparkNuxtNM:
  movieparkAdonisNM: